spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isengardinventory
    username: root
    password: 193244
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: isengard-inventory