spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    name: isengard-supermarket
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate